#!/usr/bin/env python3
"""CVAT-style manual BEV annotation export -> training occupancy/visibility labels.

Expected manual folder:
  data/bev/manual_annotated/<dataset>_120x120_annotation/
    labelmap.txt
    SegmentationClass/sample_000000.png

Output:
  data/bev/manual_labels/<dataset>/
    occupancy_npy/*.npy      uint8, 0=obstacle, 1=drivable
    visibility_npy/*.npy     uint8, 0=unseen, 1=visible
    occupancy_png/*.png      indexed PNG preserving occupancy ids
    visibility_png/*.png     indexed PNG preserving visibility ids
    review_png/*.png         visual inspection images
    labels.csv
"""
from __future__ import annotations

import argparse
import csv
import json
import pathlib
import re
import sys

import cv2
import numpy as np
from PIL import Image

_HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))

from bev_label import BevSpec, raycast_visible  # noqa: E402
from gather_annotations import spec_from_meta  # noqa: E402
import slab_render as sr  # noqa: E402


def infer_dataset_name(manual_dir):
    """Infer `raws1` from `raws1_120x120_annotation`."""
    name = pathlib.Path(manual_dir).name
    m = re.match(r"^(.+)_\d+x\d+_annotation$", name)
    if not m:
        raise ValueError(f"manual annotation folder name must be <dataset>_<H>x<W>_annotation: {name}")
    return m.group(1)


def load_labelmap_color(manual_dir, label="occupancy"):
    """Read CVAT labelmap.txt and return the RGB color tuple for `label`."""
    path = pathlib.Path(manual_dir) / "labelmap.txt"
    if not path.exists():
        raise FileNotFoundError(path)
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split(":")
        if len(parts) >= 2 and parts[0] == label:
            return tuple(int(v) for v in parts[1].split(","))
    raise ValueError(f"{path} has no {label!r} entry")


def mask_rgb_to_occupancy(rgb, occupancy_color, color_tol=8):
    """RGB mask -> uint8 occupancy using repo convention: 0=obstacle, 1=drivable."""
    img = np.asarray(rgb)
    if img.ndim != 3 or img.shape[2] != 3:
        raise ValueError(f"manual mask must be RGB, got shape {img.shape}")
    color = np.asarray(occupancy_color, dtype=np.int16)
    dist = np.max(np.abs(img.astype(np.int16) - color), axis=-1)
    obstacle = dist <= int(color_tol)
    return np.where(obstacle, 0, 1).astype(np.uint8)


def _write_readme(path):
    path.write_text(
        "# Manual BEV labels\n\n"
        "Generated from `data/bev/manual_annotated/<dataset>_120x120_annotation/SegmentationClass`.\n\n"
        "- `occupancy_npy/*.npy`: uint8 `(NX, NY)`, `0=obstacle`, `1=drivable`.\n"
        "- `visibility_npy/*.npy`: uint8 `(NX, NY)`, `0=unseen`, `1=visible`.\n"
        "- `visibility` is regenerated by `raycast_visible` from the manual occupancy mask.\n"
        "- `occupancy_png/*.png` and `visibility_png/*.png` preserve the same class ids as indexed PNGs.\n"
        "- `review_png/*.png` is for visual inspection only.\n",
        encoding="utf-8",
    )


def generate_manual_labels(manual_dir, dataset_dir, out_root, name="", color_tol=8,
                           ray_step=0.25, review_scale=6):
    """Generate labels for one manual annotation folder.

    Returns a small stats dict for tests and CLI reporting.
    """
    manual = pathlib.Path(manual_dir)
    dataset_name = name or infer_dataset_name(manual)
    dataset = pathlib.Path(dataset_dir)
    samples = sorted((manual / "SegmentationClass").glob("sample_*.png"))
    if not samples:
        raise FileNotFoundError(f"no sample_*.png under {manual / 'SegmentationClass'}")

    ds_samples = sorted(d for d in dataset.glob("sample_*") if d.is_dir())
    if not ds_samples:
        raise FileNotFoundError(f"no sample_* directories under {dataset}")
    spec = spec_from_meta(ds_samples[0])
    expected_shape = (spec.NX, spec.NY)
    occ_color = load_labelmap_color(manual, "occupancy")

    root = pathlib.Path(out_root) / dataset_name
    for sub in ("occupancy_npy", "visibility_npy", "occupancy_png", "visibility_png", "review_png"):
        (root / sub).mkdir(parents=True, exist_ok=True)

    rows = []
    for mask_path in samples:
        sample = mask_path.stem
        rgb = np.array(Image.open(mask_path).convert("RGB"))
        if rgb.shape[:2] != expected_shape:
            raise ValueError(f"{mask_path} shape {rgb.shape[:2]} != {expected_shape}")
        occupancy = mask_rgb_to_occupancy(rgb, occ_color, color_tol=color_tol)
        obstacle = occupancy == 0
        visibility = raycast_visible(obstacle, spec, step_deg=ray_step).astype(np.uint8)

        np.save(root / "occupancy_npy" / f"{sample}.npy", occupancy)
        np.save(root / "visibility_npy" / f"{sample}.npy", visibility)
        sr.save_indexed(root / "occupancy_png" / f"{sample}.png", occupancy, sr.PALETTE_OCC)
        sr.save_indexed(root / "visibility_png" / f"{sample}.png", visibility, sr.PALETTE_VIS)

        ipm_path = dataset / sample / "ipm_rgb.png"
        ipm = cv2.imread(str(ipm_path)) if ipm_path.exists() else None
        if review_scale:
            review = sr.review_png(occupancy, visibility, spec, scale=review_scale, ipm=ipm)
            cv2.imwrite(str(root / "review_png" / f"{sample}.png"), review)

        rows.append({
            "sample": sample,
            "occupancy_npy": f"occupancy_npy/{sample}.npy",
            "visibility_npy": f"visibility_npy/{sample}.npy",
            "occupancy_png": f"occupancy_png/{sample}.png",
            "visibility_png": f"visibility_png/{sample}.png",
            "review_png": f"review_png/{sample}.png",
            "obstacle_cells": int(obstacle.sum()),
            "obstacle_pct": float(obstacle.mean() * 100.0),
            "visible_cells": int(visibility.sum()),
            "visible_pct": float(visibility.mean() * 100.0),
        })

    with (root / "labels.csv").open("w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    _write_readme(root / "README.md")

    return {
        "dataset": dataset_name,
        "samples": len(rows),
        "out": str(root),
        "spec": {
            "XF": spec.XF,
            "XR": spec.XR,
            "YH": spec.YH,
            "RES": spec.RES,
            "NX": spec.NX,
            "NY": spec.NY,
        },
        "obstacle_pct_min": min(r["obstacle_pct"] for r in rows),
        "obstacle_pct_max": max(r["obstacle_pct"] for r in rows),
        "visible_pct_min": min(r["visible_pct"] for r in rows),
        "visible_pct_max": max(r["visible_pct"] for r in rows),
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--manual-dir", required=True,
                    help="manual_annotated/<dataset>_120x120_annotation folder")
    ap.add_argument("--dataset-root", default=str(_HERE.parent.parent / "data" / "bev" / "dataset"),
                    help="root containing original dataset folders")
    ap.add_argument("--out", default=str(_HERE.parent.parent / "data" / "bev" / "manual_labels"),
                    help="output root; writes <out>/<dataset>")
    ap.add_argument("--name", default="",
                    help="dataset/output folder name; default inferred from manual-dir")
    ap.add_argument("--color-tol", type=int, default=8,
                    help="RGB tolerance for occupancy labelmap color")
    ap.add_argument("--ray-step", type=float, default=0.25,
                    help="raycast visibility angular step in degrees")
    ap.add_argument("--review-scale", type=int, default=6,
                    help="review_png BEV scale; 0 skips review images")
    a = ap.parse_args()

    dataset_name = a.name or infer_dataset_name(a.manual_dir)
    dataset_dir = pathlib.Path(a.dataset_root) / dataset_name
    stats = generate_manual_labels(a.manual_dir, dataset_dir, a.out, name=dataset_name,
                                   color_tol=a.color_tol, ray_step=a.ray_step,
                                   review_scale=a.review_scale)
    b = stats["spec"]
    print(f"BEV {b['NX']}x{b['NY']} (XF={b['XF']} XR={b['XR']} YH={b['YH']} RES={b['RES']})")
    print(f"generated {stats['samples']} samples -> {stats['out']}")
    print("obstacle_pct range "
          f"{stats['obstacle_pct_min']:.2f}..{stats['obstacle_pct_max']:.2f}")
    print("visible_pct range "
          f"{stats['visible_pct_min']:.2f}..{stats['visible_pct_max']:.2f}")


if __name__ == "__main__":
    main()
